project:
  type: website

website:
  title: "Edge of Chaos Collective"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: stories/index.qmd
        text: Stories
      - href: music/index.qmd
        text: Music
      - href: games/index.qmd
        text: Games
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

